### ISSUE TITLE
Possible to add a delay to start animation?

### ISSUE THREAD

**Issue by hrishikesh-k** [prjct-samwest/scrollCue#1]
Hello.

Thanks for this amazing library. It does the perfect job for my website. However, I was wondering if we can add a slight delay for a certain animation to start. That would just be a cherry on top.

**Comment by prjct-samwest** [comment]
Hello.

Thanks for the report and support .
Unfortunately, the delay function is not implemented for the animation itself.

However, it's a bit rough, but you may be able to delay it in the following way.

HTML
```html
<img src="example.jpg" data-cue="fadeIn" data-addClass="delay">
```

CSS
```css
.delay{
  animation-delay: 2s !important;
}
```

Thank you.

**Comment by hrishikesh-k** [comment]
Works perfectly, thanks a lot!
