### ISSUE TITLE
Issue on Safari

### ISSUE THREAD

**Issue by elemis** [prjct-samwest/scrollCue#5]
If scrollcue is used at the top of the page, the elements don’t show until you scroll a little bit on Safari. Please check http://themes.iki-bir.com/sandbox/index7.html for demonstration. What could be the issue here? Any tips to overcome this? Thanks.

**Comment by prjct-samwest** [comment]
I don't know the exact cause, but can you modify scripts.js as follows? Thank you,
```
function enableScrollCue() {
    scrollCue.init({
        interval: -400,
        duration: 700,
        percentage: 0.8,
        enable : false,
    });
    $(window).on('load',function (){
        scrollCue.enable();
    });
};
enableScrollCue();
```

**Comment by elemis** [comment]
Thank you for replying. Tried the code but now it doesn't work at all. Please check: http://themes.iki-bir.com/sb2/index7.html

**Comment by prjct-samwest** [comment]
It seems that the load event is not working for some reason :(  
Can you please try the following?

```
function enableScrollCue() {
    scrollCue.init({
        interval: -400,
        duration: 700,
        percentage: 0.8,
        enable : false,
    });
    $(window).on('load',function (){
        scrollCue.enable();
        $(window).trigger('resize');  // added
    });
};
enableScrollCue();
```

**Comment by elemis** [comment]
Still the same :( Sorry for taking your time.

**Comment by prjct-samwest** [comment]
Hmm, you might be able to go with simply running the update method. I'm not sure, but.
I'm sorry to bother you.
```
function enableScrollCue() {
	scrollCue.init({
		interval: -400,
		duration: 700,
		percentage: 0.8
	});
};
enableScrollCue();
scrollCue.update();  // try this!
```

**Comment by elemis** [comment]
It worked! Thank you very much for your help.
